
/*
Auto-generated by CVXPYgen on January 30, 2024 at 06:19:45.
Content: Example program for updating parameters, solving, and inspecting the result.
*/

#include <stdio.h>
#include "cpg_workspace.h"
#include "cpg_solve.h"

static int i;

int main(int argc, char *argv[]){

  // Update first entry of every user-defined parameter
  cpg_update_q(0, -0.49879199172902516368);
  cpg_update_r_0(0, -0.79457200579197162504);
  cpg_update_v_0(0, -0.08917256025987954637);
  cpg_update_m_0(0.34496166364976466046);
  cpg_update_t_f_A(0, 0.35246024032513029178);
  cpg_update_t_f_B(0, 0.64699788390547796624);
  cpg_update_t_f_B_g(0, -0.30356301049350992161);
  cpg_update_alpha(-0.90704619342936532167);
  cpg_update_theta_cos(0.06653294408030772933);
  cpg_update_n_hat(0, 0.39867009488931970385);
  cpg_update_v_max(0.40240691004874024062);
  cpg_update_c(0, 0.53706736464446225288);
  cpg_update_c_q(0, 0.77236846991282637198);
  cpg_update_rho_2_exp_z_0(0, 0.19304711261597937155);
  cpg_update_rho_2_exp_z_0_z_0(0, 0.71752435950126247644);
  cpg_update_rho_1_exp_z_0(0, 1.15119988669098272105);
  cpg_update_rho_1_exp_z_0_z_0(0, -0.33898989212802277393);

  // Solve the problem instance
  cpg_solve();

  // Print objective function value
  printf("obj = %f\n", CPG_Result.info->obj_val);

  // Print primal solution
  for(i=0; i<720; i++) {
    printf("x[%d] = %f\n", i, CPG_Result.prim->x[i]);
  }
  for(i=0; i<120; i++) {
    printf("sigma[%d] = %f\n", i, CPG_Result.prim->sigma[i]);
  }
  for(i=0; i<360; i++) {
    printf("u[%d] = %f\n", i, CPG_Result.prim->u[i]);
  }
  for(i=0; i<120; i++) {
    printf("z[%d] = %f\n", i, CPG_Result.prim->z[i]);
  }

  // Print dual solution
  for(i=0; i<3; i++) {
    printf("d0[%d] = %f\n", i, CPG_Result.dual->d0[i]);
  }
  for(i=0; i<3; i++) {
    printf("d1[%d] = %f\n", i, CPG_Result.dual->d1[i]);
  }
  printf("d2 = %f\n", CPG_Result.dual->d2);
  for(i=0; i<3; i++) {
    printf("d3[%d] = %f\n", i, CPG_Result.dual->d3[i]);
  }
  printf("d4 = %f\n", CPG_Result.dual->d4);
  for(i=0; i<3; i++) {
    printf("d5[%d] = %f\n", i, CPG_Result.dual->d5[i]);
  }
  for(i=0; i<3; i++) {
    printf("d6[%d] = %f\n", i, CPG_Result.dual->d6[i]);
  }
  for(i=0; i<120; i++) {
    printf("d7[%d] = %f\n", i, CPG_Result.dual->d7[i]);
  }
  for(i=0; i<18; i++) {
    printf("d8[%d] = %f\n", i, CPG_Result.dual->d8[i]);
  }
  printf("d9 = %f\n", CPG_Result.dual->d9);
  for(i=0; i<18; i++) {
    printf("d10[%d] = %f\n", i, CPG_Result.dual->d10[i]);
  }
  printf("d11 = %f\n", CPG_Result.dual->d11);
  for(i=0; i<18; i++) {
    printf("d12[%d] = %f\n", i, CPG_Result.dual->d12[i]);
  }
  printf("d13 = %f\n", CPG_Result.dual->d13);
  for(i=0; i<18; i++) {
    printf("d14[%d] = %f\n", i, CPG_Result.dual->d14[i]);
  }
  printf("d15 = %f\n", CPG_Result.dual->d15);
  for(i=0; i<18; i++) {
    printf("d16[%d] = %f\n", i, CPG_Result.dual->d16[i]);
  }
  printf("d17 = %f\n", CPG_Result.dual->d17);
  for(i=0; i<18; i++) {
    printf("d18[%d] = %f\n", i, CPG_Result.dual->d18[i]);
  }
  printf("d19 = %f\n", CPG_Result.dual->d19);
  for(i=0; i<18; i++) {
    printf("d20[%d] = %f\n", i, CPG_Result.dual->d20[i]);
  }
  printf("d21 = %f\n", CPG_Result.dual->d21);
  for(i=0; i<18; i++) {
    printf("d22[%d] = %f\n", i, CPG_Result.dual->d22[i]);
  }
  printf("d23 = %f\n", CPG_Result.dual->d23);
  for(i=0; i<18; i++) {
    printf("d24[%d] = %f\n", i, CPG_Result.dual->d24[i]);
  }
  printf("d25 = %f\n", CPG_Result.dual->d25);
  for(i=0; i<18; i++) {
    printf("d26[%d] = %f\n", i, CPG_Result.dual->d26[i]);
  }
  printf("d27 = %f\n", CPG_Result.dual->d27);
  for(i=0; i<18; i++) {
    printf("d28[%d] = %f\n", i, CPG_Result.dual->d28[i]);
  }
  printf("d29 = %f\n", CPG_Result.dual->d29);
  for(i=0; i<18; i++) {
    printf("d30[%d] = %f\n", i, CPG_Result.dual->d30[i]);
  }
  printf("d31 = %f\n", CPG_Result.dual->d31);
  for(i=0; i<18; i++) {
    printf("d32[%d] = %f\n", i, CPG_Result.dual->d32[i]);
  }
  printf("d33 = %f\n", CPG_Result.dual->d33);
  for(i=0; i<18; i++) {
    printf("d34[%d] = %f\n", i, CPG_Result.dual->d34[i]);
  }
  printf("d35 = %f\n", CPG_Result.dual->d35);
  for(i=0; i<18; i++) {
    printf("d36[%d] = %f\n", i, CPG_Result.dual->d36[i]);
  }
  printf("d37 = %f\n", CPG_Result.dual->d37);
  for(i=0; i<18; i++) {
    printf("d38[%d] = %f\n", i, CPG_Result.dual->d38[i]);
  }
  printf("d39 = %f\n", CPG_Result.dual->d39);
  for(i=0; i<18; i++) {
    printf("d40[%d] = %f\n", i, CPG_Result.dual->d40[i]);
  }
  printf("d41 = %f\n", CPG_Result.dual->d41);
  for(i=0; i<18; i++) {
    printf("d42[%d] = %f\n", i, CPG_Result.dual->d42[i]);
  }
  printf("d43 = %f\n", CPG_Result.dual->d43);
  for(i=0; i<18; i++) {
    printf("d44[%d] = %f\n", i, CPG_Result.dual->d44[i]);
  }
  printf("d45 = %f\n", CPG_Result.dual->d45);
  for(i=0; i<18; i++) {
    printf("d46[%d] = %f\n", i, CPG_Result.dual->d46[i]);
  }
  printf("d47 = %f\n", CPG_Result.dual->d47);
  for(i=0; i<18; i++) {
    printf("d48[%d] = %f\n", i, CPG_Result.dual->d48[i]);
  }
  printf("d49 = %f\n", CPG_Result.dual->d49);
  for(i=0; i<18; i++) {
    printf("d50[%d] = %f\n", i, CPG_Result.dual->d50[i]);
  }
  printf("d51 = %f\n", CPG_Result.dual->d51);
  for(i=0; i<18; i++) {
    printf("d52[%d] = %f\n", i, CPG_Result.dual->d52[i]);
  }
  printf("d53 = %f\n", CPG_Result.dual->d53);
  for(i=0; i<18; i++) {
    printf("d54[%d] = %f\n", i, CPG_Result.dual->d54[i]);
  }
  printf("d55 = %f\n", CPG_Result.dual->d55);
  for(i=0; i<18; i++) {
    printf("d56[%d] = %f\n", i, CPG_Result.dual->d56[i]);
  }
  printf("d57 = %f\n", CPG_Result.dual->d57);
  for(i=0; i<18; i++) {
    printf("d58[%d] = %f\n", i, CPG_Result.dual->d58[i]);
  }
  printf("d59 = %f\n", CPG_Result.dual->d59);
  for(i=0; i<18; i++) {
    printf("d60[%d] = %f\n", i, CPG_Result.dual->d60[i]);
  }
  printf("d61 = %f\n", CPG_Result.dual->d61);
  for(i=0; i<18; i++) {
    printf("d62[%d] = %f\n", i, CPG_Result.dual->d62[i]);
  }
  printf("d63 = %f\n", CPG_Result.dual->d63);
  for(i=0; i<18; i++) {
    printf("d64[%d] = %f\n", i, CPG_Result.dual->d64[i]);
  }
  printf("d65 = %f\n", CPG_Result.dual->d65);
  for(i=0; i<18; i++) {
    printf("d66[%d] = %f\n", i, CPG_Result.dual->d66[i]);
  }
  printf("d67 = %f\n", CPG_Result.dual->d67);
  for(i=0; i<18; i++) {
    printf("d68[%d] = %f\n", i, CPG_Result.dual->d68[i]);
  }
  printf("d69 = %f\n", CPG_Result.dual->d69);
  for(i=0; i<18; i++) {
    printf("d70[%d] = %f\n", i, CPG_Result.dual->d70[i]);
  }
  printf("d71 = %f\n", CPG_Result.dual->d71);
  for(i=0; i<18; i++) {
    printf("d72[%d] = %f\n", i, CPG_Result.dual->d72[i]);
  }
  printf("d73 = %f\n", CPG_Result.dual->d73);
  for(i=0; i<18; i++) {
    printf("d74[%d] = %f\n", i, CPG_Result.dual->d74[i]);
  }
  printf("d75 = %f\n", CPG_Result.dual->d75);
  for(i=0; i<18; i++) {
    printf("d76[%d] = %f\n", i, CPG_Result.dual->d76[i]);
  }
  printf("d77 = %f\n", CPG_Result.dual->d77);
  for(i=0; i<18; i++) {
    printf("d78[%d] = %f\n", i, CPG_Result.dual->d78[i]);
  }
  printf("d79 = %f\n", CPG_Result.dual->d79);
  for(i=0; i<18; i++) {
    printf("d80[%d] = %f\n", i, CPG_Result.dual->d80[i]);
  }
  printf("d81 = %f\n", CPG_Result.dual->d81);
  for(i=0; i<18; i++) {
    printf("d82[%d] = %f\n", i, CPG_Result.dual->d82[i]);
  }
  printf("d83 = %f\n", CPG_Result.dual->d83);
  for(i=0; i<18; i++) {
    printf("d84[%d] = %f\n", i, CPG_Result.dual->d84[i]);
  }
  printf("d85 = %f\n", CPG_Result.dual->d85);
  for(i=0; i<18; i++) {
    printf("d86[%d] = %f\n", i, CPG_Result.dual->d86[i]);
  }
  printf("d87 = %f\n", CPG_Result.dual->d87);
  for(i=0; i<18; i++) {
    printf("d88[%d] = %f\n", i, CPG_Result.dual->d88[i]);
  }
  printf("d89 = %f\n", CPG_Result.dual->d89);
  for(i=0; i<18; i++) {
    printf("d90[%d] = %f\n", i, CPG_Result.dual->d90[i]);
  }
  printf("d91 = %f\n", CPG_Result.dual->d91);
  for(i=0; i<18; i++) {
    printf("d92[%d] = %f\n", i, CPG_Result.dual->d92[i]);
  }
  printf("d93 = %f\n", CPG_Result.dual->d93);
  for(i=0; i<18; i++) {
    printf("d94[%d] = %f\n", i, CPG_Result.dual->d94[i]);
  }
  printf("d95 = %f\n", CPG_Result.dual->d95);
  for(i=0; i<18; i++) {
    printf("d96[%d] = %f\n", i, CPG_Result.dual->d96[i]);
  }
  printf("d97 = %f\n", CPG_Result.dual->d97);
  for(i=0; i<18; i++) {
    printf("d98[%d] = %f\n", i, CPG_Result.dual->d98[i]);
  }
  printf("d99 = %f\n", CPG_Result.dual->d99);
  for(i=0; i<18; i++) {
    printf("d100[%d] = %f\n", i, CPG_Result.dual->d100[i]);
  }
  printf("d101 = %f\n", CPG_Result.dual->d101);
  for(i=0; i<18; i++) {
    printf("d102[%d] = %f\n", i, CPG_Result.dual->d102[i]);
  }
  printf("d103 = %f\n", CPG_Result.dual->d103);
  for(i=0; i<18; i++) {
    printf("d104[%d] = %f\n", i, CPG_Result.dual->d104[i]);
  }
  printf("d105 = %f\n", CPG_Result.dual->d105);
  for(i=0; i<18; i++) {
    printf("d106[%d] = %f\n", i, CPG_Result.dual->d106[i]);
  }
  printf("d107 = %f\n", CPG_Result.dual->d107);
  for(i=0; i<18; i++) {
    printf("d108[%d] = %f\n", i, CPG_Result.dual->d108[i]);
  }
  printf("d109 = %f\n", CPG_Result.dual->d109);
  for(i=0; i<18; i++) {
    printf("d110[%d] = %f\n", i, CPG_Result.dual->d110[i]);
  }
  printf("d111 = %f\n", CPG_Result.dual->d111);
  for(i=0; i<18; i++) {
    printf("d112[%d] = %f\n", i, CPG_Result.dual->d112[i]);
  }
  printf("d113 = %f\n", CPG_Result.dual->d113);
  for(i=0; i<18; i++) {
    printf("d114[%d] = %f\n", i, CPG_Result.dual->d114[i]);
  }
  printf("d115 = %f\n", CPG_Result.dual->d115);
  for(i=0; i<18; i++) {
    printf("d116[%d] = %f\n", i, CPG_Result.dual->d116[i]);
  }
  printf("d117 = %f\n", CPG_Result.dual->d117);
  for(i=0; i<18; i++) {
    printf("d118[%d] = %f\n", i, CPG_Result.dual->d118[i]);
  }
  printf("d119 = %f\n", CPG_Result.dual->d119);
  for(i=0; i<18; i++) {
    printf("d120[%d] = %f\n", i, CPG_Result.dual->d120[i]);
  }
  printf("d121 = %f\n", CPG_Result.dual->d121);
  for(i=0; i<18; i++) {
    printf("d122[%d] = %f\n", i, CPG_Result.dual->d122[i]);
  }
  printf("d123 = %f\n", CPG_Result.dual->d123);
  for(i=0; i<18; i++) {
    printf("d124[%d] = %f\n", i, CPG_Result.dual->d124[i]);
  }
  printf("d125 = %f\n", CPG_Result.dual->d125);
  for(i=0; i<18; i++) {
    printf("d126[%d] = %f\n", i, CPG_Result.dual->d126[i]);
  }
  printf("d127 = %f\n", CPG_Result.dual->d127);
  for(i=0; i<18; i++) {
    printf("d128[%d] = %f\n", i, CPG_Result.dual->d128[i]);
  }
  printf("d129 = %f\n", CPG_Result.dual->d129);
  for(i=0; i<18; i++) {
    printf("d130[%d] = %f\n", i, CPG_Result.dual->d130[i]);
  }
  printf("d131 = %f\n", CPG_Result.dual->d131);
  for(i=0; i<18; i++) {
    printf("d132[%d] = %f\n", i, CPG_Result.dual->d132[i]);
  }
  printf("d133 = %f\n", CPG_Result.dual->d133);
  for(i=0; i<18; i++) {
    printf("d134[%d] = %f\n", i, CPG_Result.dual->d134[i]);
  }
  printf("d135 = %f\n", CPG_Result.dual->d135);
  for(i=0; i<18; i++) {
    printf("d136[%d] = %f\n", i, CPG_Result.dual->d136[i]);
  }
  printf("d137 = %f\n", CPG_Result.dual->d137);
  for(i=0; i<18; i++) {
    printf("d138[%d] = %f\n", i, CPG_Result.dual->d138[i]);
  }
  printf("d139 = %f\n", CPG_Result.dual->d139);
  for(i=0; i<18; i++) {
    printf("d140[%d] = %f\n", i, CPG_Result.dual->d140[i]);
  }
  printf("d141 = %f\n", CPG_Result.dual->d141);
  for(i=0; i<18; i++) {
    printf("d142[%d] = %f\n", i, CPG_Result.dual->d142[i]);
  }
  printf("d143 = %f\n", CPG_Result.dual->d143);
  for(i=0; i<18; i++) {
    printf("d144[%d] = %f\n", i, CPG_Result.dual->d144[i]);
  }
  printf("d145 = %f\n", CPG_Result.dual->d145);
  for(i=0; i<18; i++) {
    printf("d146[%d] = %f\n", i, CPG_Result.dual->d146[i]);
  }
  printf("d147 = %f\n", CPG_Result.dual->d147);
  for(i=0; i<18; i++) {
    printf("d148[%d] = %f\n", i, CPG_Result.dual->d148[i]);
  }
  printf("d149 = %f\n", CPG_Result.dual->d149);
  for(i=0; i<18; i++) {
    printf("d150[%d] = %f\n", i, CPG_Result.dual->d150[i]);
  }
  printf("d151 = %f\n", CPG_Result.dual->d151);
  for(i=0; i<18; i++) {
    printf("d152[%d] = %f\n", i, CPG_Result.dual->d152[i]);
  }
  printf("d153 = %f\n", CPG_Result.dual->d153);
  for(i=0; i<18; i++) {
    printf("d154[%d] = %f\n", i, CPG_Result.dual->d154[i]);
  }
  printf("d155 = %f\n", CPG_Result.dual->d155);
  for(i=0; i<18; i++) {
    printf("d156[%d] = %f\n", i, CPG_Result.dual->d156[i]);
  }
  printf("d157 = %f\n", CPG_Result.dual->d157);
  for(i=0; i<18; i++) {
    printf("d158[%d] = %f\n", i, CPG_Result.dual->d158[i]);
  }
  printf("d159 = %f\n", CPG_Result.dual->d159);
  for(i=0; i<18; i++) {
    printf("d160[%d] = %f\n", i, CPG_Result.dual->d160[i]);
  }
  printf("d161 = %f\n", CPG_Result.dual->d161);
  for(i=0; i<18; i++) {
    printf("d162[%d] = %f\n", i, CPG_Result.dual->d162[i]);
  }
  printf("d163 = %f\n", CPG_Result.dual->d163);
  for(i=0; i<18; i++) {
    printf("d164[%d] = %f\n", i, CPG_Result.dual->d164[i]);
  }
  printf("d165 = %f\n", CPG_Result.dual->d165);
  for(i=0; i<18; i++) {
    printf("d166[%d] = %f\n", i, CPG_Result.dual->d166[i]);
  }
  printf("d167 = %f\n", CPG_Result.dual->d167);
  for(i=0; i<18; i++) {
    printf("d168[%d] = %f\n", i, CPG_Result.dual->d168[i]);
  }
  printf("d169 = %f\n", CPG_Result.dual->d169);
  for(i=0; i<18; i++) {
    printf("d170[%d] = %f\n", i, CPG_Result.dual->d170[i]);
  }
  printf("d171 = %f\n", CPG_Result.dual->d171);
  for(i=0; i<18; i++) {
    printf("d172[%d] = %f\n", i, CPG_Result.dual->d172[i]);
  }
  printf("d173 = %f\n", CPG_Result.dual->d173);
  for(i=0; i<18; i++) {
    printf("d174[%d] = %f\n", i, CPG_Result.dual->d174[i]);
  }
  printf("d175 = %f\n", CPG_Result.dual->d175);
  for(i=0; i<18; i++) {
    printf("d176[%d] = %f\n", i, CPG_Result.dual->d176[i]);
  }
  printf("d177 = %f\n", CPG_Result.dual->d177);
  for(i=0; i<18; i++) {
    printf("d178[%d] = %f\n", i, CPG_Result.dual->d178[i]);
  }
  printf("d179 = %f\n", CPG_Result.dual->d179);
  for(i=0; i<18; i++) {
    printf("d180[%d] = %f\n", i, CPG_Result.dual->d180[i]);
  }
  printf("d181 = %f\n", CPG_Result.dual->d181);
  for(i=0; i<18; i++) {
    printf("d182[%d] = %f\n", i, CPG_Result.dual->d182[i]);
  }
  printf("d183 = %f\n", CPG_Result.dual->d183);
  for(i=0; i<18; i++) {
    printf("d184[%d] = %f\n", i, CPG_Result.dual->d184[i]);
  }
  printf("d185 = %f\n", CPG_Result.dual->d185);
  for(i=0; i<18; i++) {
    printf("d186[%d] = %f\n", i, CPG_Result.dual->d186[i]);
  }
  printf("d187 = %f\n", CPG_Result.dual->d187);
  for(i=0; i<18; i++) {
    printf("d188[%d] = %f\n", i, CPG_Result.dual->d188[i]);
  }
  printf("d189 = %f\n", CPG_Result.dual->d189);
  for(i=0; i<18; i++) {
    printf("d190[%d] = %f\n", i, CPG_Result.dual->d190[i]);
  }
  printf("d191 = %f\n", CPG_Result.dual->d191);
  for(i=0; i<18; i++) {
    printf("d192[%d] = %f\n", i, CPG_Result.dual->d192[i]);
  }
  printf("d193 = %f\n", CPG_Result.dual->d193);
  for(i=0; i<18; i++) {
    printf("d194[%d] = %f\n", i, CPG_Result.dual->d194[i]);
  }
  printf("d195 = %f\n", CPG_Result.dual->d195);
  for(i=0; i<18; i++) {
    printf("d196[%d] = %f\n", i, CPG_Result.dual->d196[i]);
  }
  printf("d197 = %f\n", CPG_Result.dual->d197);
  for(i=0; i<18; i++) {
    printf("d198[%d] = %f\n", i, CPG_Result.dual->d198[i]);
  }
  printf("d199 = %f\n", CPG_Result.dual->d199);
  for(i=0; i<18; i++) {
    printf("d200[%d] = %f\n", i, CPG_Result.dual->d200[i]);
  }
  printf("d201 = %f\n", CPG_Result.dual->d201);
  for(i=0; i<18; i++) {
    printf("d202[%d] = %f\n", i, CPG_Result.dual->d202[i]);
  }
  printf("d203 = %f\n", CPG_Result.dual->d203);
  for(i=0; i<18; i++) {
    printf("d204[%d] = %f\n", i, CPG_Result.dual->d204[i]);
  }
  printf("d205 = %f\n", CPG_Result.dual->d205);
  for(i=0; i<18; i++) {
    printf("d206[%d] = %f\n", i, CPG_Result.dual->d206[i]);
  }
  printf("d207 = %f\n", CPG_Result.dual->d207);
  for(i=0; i<18; i++) {
    printf("d208[%d] = %f\n", i, CPG_Result.dual->d208[i]);
  }
  printf("d209 = %f\n", CPG_Result.dual->d209);
  for(i=0; i<18; i++) {
    printf("d210[%d] = %f\n", i, CPG_Result.dual->d210[i]);
  }
  printf("d211 = %f\n", CPG_Result.dual->d211);
  for(i=0; i<18; i++) {
    printf("d212[%d] = %f\n", i, CPG_Result.dual->d212[i]);
  }
  printf("d213 = %f\n", CPG_Result.dual->d213);
  for(i=0; i<18; i++) {
    printf("d214[%d] = %f\n", i, CPG_Result.dual->d214[i]);
  }
  printf("d215 = %f\n", CPG_Result.dual->d215);
  for(i=0; i<18; i++) {
    printf("d216[%d] = %f\n", i, CPG_Result.dual->d216[i]);
  }
  printf("d217 = %f\n", CPG_Result.dual->d217);
  for(i=0; i<18; i++) {
    printf("d218[%d] = %f\n", i, CPG_Result.dual->d218[i]);
  }
  printf("d219 = %f\n", CPG_Result.dual->d219);
  for(i=0; i<18; i++) {
    printf("d220[%d] = %f\n", i, CPG_Result.dual->d220[i]);
  }
  printf("d221 = %f\n", CPG_Result.dual->d221);
  for(i=0; i<18; i++) {
    printf("d222[%d] = %f\n", i, CPG_Result.dual->d222[i]);
  }
  printf("d223 = %f\n", CPG_Result.dual->d223);
  for(i=0; i<18; i++) {
    printf("d224[%d] = %f\n", i, CPG_Result.dual->d224[i]);
  }
  printf("d225 = %f\n", CPG_Result.dual->d225);
  for(i=0; i<18; i++) {
    printf("d226[%d] = %f\n", i, CPG_Result.dual->d226[i]);
  }
  printf("d227 = %f\n", CPG_Result.dual->d227);
  for(i=0; i<18; i++) {
    printf("d228[%d] = %f\n", i, CPG_Result.dual->d228[i]);
  }
  printf("d229 = %f\n", CPG_Result.dual->d229);
  for(i=0; i<18; i++) {
    printf("d230[%d] = %f\n", i, CPG_Result.dual->d230[i]);
  }
  printf("d231 = %f\n", CPG_Result.dual->d231);
  for(i=0; i<18; i++) {
    printf("d232[%d] = %f\n", i, CPG_Result.dual->d232[i]);
  }
  printf("d233 = %f\n", CPG_Result.dual->d233);
  for(i=0; i<18; i++) {
    printf("d234[%d] = %f\n", i, CPG_Result.dual->d234[i]);
  }
  printf("d235 = %f\n", CPG_Result.dual->d235);
  for(i=0; i<18; i++) {
    printf("d236[%d] = %f\n", i, CPG_Result.dual->d236[i]);
  }
  printf("d237 = %f\n", CPG_Result.dual->d237);
  for(i=0; i<18; i++) {
    printf("d238[%d] = %f\n", i, CPG_Result.dual->d238[i]);
  }
  printf("d239 = %f\n", CPG_Result.dual->d239);
  for(i=0; i<18; i++) {
    printf("d240[%d] = %f\n", i, CPG_Result.dual->d240[i]);
  }
  printf("d241 = %f\n", CPG_Result.dual->d241);
  for(i=0; i<18; i++) {
    printf("d242[%d] = %f\n", i, CPG_Result.dual->d242[i]);
  }
  printf("d243 = %f\n", CPG_Result.dual->d243);
  for(i=0; i<18; i++) {
    printf("d244[%d] = %f\n", i, CPG_Result.dual->d244[i]);
  }
  printf("d245 = %f\n", CPG_Result.dual->d245);
  printf("d246 = %f\n", CPG_Result.dual->d246);
  printf("d247 = %f\n", CPG_Result.dual->d247);
  printf("d248 = %f\n", CPG_Result.dual->d248);
  for(i=0; i<3; i++) {
    printf("d249[%d] = %f\n", i, CPG_Result.dual->d249[i]);
  }
  printf("d250 = %f\n", CPG_Result.dual->d250);
  printf("d251 = %f\n", CPG_Result.dual->d251);
  printf("d252 = %f\n", CPG_Result.dual->d252);
  printf("d253 = %f\n", CPG_Result.dual->d253);
  printf("d254 = %f\n", CPG_Result.dual->d254);
  for(i=0; i<3; i++) {
    printf("d255[%d] = %f\n", i, CPG_Result.dual->d255[i]);
  }
  printf("d256 = %f\n", CPG_Result.dual->d256);
  printf("d257 = %f\n", CPG_Result.dual->d257);
  printf("d258 = %f\n", CPG_Result.dual->d258);
  printf("d259 = %f\n", CPG_Result.dual->d259);
  printf("d260 = %f\n", CPG_Result.dual->d260);
  for(i=0; i<3; i++) {
    printf("d261[%d] = %f\n", i, CPG_Result.dual->d261[i]);
  }
  printf("d262 = %f\n", CPG_Result.dual->d262);
  printf("d263 = %f\n", CPG_Result.dual->d263);
  printf("d264 = %f\n", CPG_Result.dual->d264);
  printf("d265 = %f\n", CPG_Result.dual->d265);
  printf("d266 = %f\n", CPG_Result.dual->d266);
  for(i=0; i<3; i++) {
    printf("d267[%d] = %f\n", i, CPG_Result.dual->d267[i]);
  }
  printf("d268 = %f\n", CPG_Result.dual->d268);
  printf("d269 = %f\n", CPG_Result.dual->d269);
  printf("d270 = %f\n", CPG_Result.dual->d270);
  printf("d271 = %f\n", CPG_Result.dual->d271);
  printf("d272 = %f\n", CPG_Result.dual->d272);
  for(i=0; i<3; i++) {
    printf("d273[%d] = %f\n", i, CPG_Result.dual->d273[i]);
  }
  printf("d274 = %f\n", CPG_Result.dual->d274);
  printf("d275 = %f\n", CPG_Result.dual->d275);
  printf("d276 = %f\n", CPG_Result.dual->d276);
  printf("d277 = %f\n", CPG_Result.dual->d277);
  printf("d278 = %f\n", CPG_Result.dual->d278);
  for(i=0; i<3; i++) {
    printf("d279[%d] = %f\n", i, CPG_Result.dual->d279[i]);
  }
  printf("d280 = %f\n", CPG_Result.dual->d280);
  printf("d281 = %f\n", CPG_Result.dual->d281);
  printf("d282 = %f\n", CPG_Result.dual->d282);
  printf("d283 = %f\n", CPG_Result.dual->d283);
  printf("d284 = %f\n", CPG_Result.dual->d284);
  for(i=0; i<3; i++) {
    printf("d285[%d] = %f\n", i, CPG_Result.dual->d285[i]);
  }
  printf("d286 = %f\n", CPG_Result.dual->d286);
  printf("d287 = %f\n", CPG_Result.dual->d287);
  printf("d288 = %f\n", CPG_Result.dual->d288);
  printf("d289 = %f\n", CPG_Result.dual->d289);
  printf("d290 = %f\n", CPG_Result.dual->d290);
  for(i=0; i<3; i++) {
    printf("d291[%d] = %f\n", i, CPG_Result.dual->d291[i]);
  }
  printf("d292 = %f\n", CPG_Result.dual->d292);
  printf("d293 = %f\n", CPG_Result.dual->d293);
  printf("d294 = %f\n", CPG_Result.dual->d294);
  printf("d295 = %f\n", CPG_Result.dual->d295);
  printf("d296 = %f\n", CPG_Result.dual->d296);
  for(i=0; i<3; i++) {
    printf("d297[%d] = %f\n", i, CPG_Result.dual->d297[i]);
  }
  printf("d298 = %f\n", CPG_Result.dual->d298);
  printf("d299 = %f\n", CPG_Result.dual->d299);
  printf("d300 = %f\n", CPG_Result.dual->d300);
  printf("d301 = %f\n", CPG_Result.dual->d301);
  printf("d302 = %f\n", CPG_Result.dual->d302);
  for(i=0; i<3; i++) {
    printf("d303[%d] = %f\n", i, CPG_Result.dual->d303[i]);
  }
  printf("d304 = %f\n", CPG_Result.dual->d304);
  printf("d305 = %f\n", CPG_Result.dual->d305);
  printf("d306 = %f\n", CPG_Result.dual->d306);
  printf("d307 = %f\n", CPG_Result.dual->d307);
  printf("d308 = %f\n", CPG_Result.dual->d308);
  for(i=0; i<3; i++) {
    printf("d309[%d] = %f\n", i, CPG_Result.dual->d309[i]);
  }
  printf("d310 = %f\n", CPG_Result.dual->d310);
  printf("d311 = %f\n", CPG_Result.dual->d311);
  printf("d312 = %f\n", CPG_Result.dual->d312);
  printf("d313 = %f\n", CPG_Result.dual->d313);
  printf("d314 = %f\n", CPG_Result.dual->d314);
  for(i=0; i<3; i++) {
    printf("d315[%d] = %f\n", i, CPG_Result.dual->d315[i]);
  }
  printf("d316 = %f\n", CPG_Result.dual->d316);
  printf("d317 = %f\n", CPG_Result.dual->d317);
  printf("d318 = %f\n", CPG_Result.dual->d318);
  printf("d319 = %f\n", CPG_Result.dual->d319);
  printf("d320 = %f\n", CPG_Result.dual->d320);
  for(i=0; i<3; i++) {
    printf("d321[%d] = %f\n", i, CPG_Result.dual->d321[i]);
  }
  printf("d322 = %f\n", CPG_Result.dual->d322);
  printf("d323 = %f\n", CPG_Result.dual->d323);
  printf("d324 = %f\n", CPG_Result.dual->d324);
  printf("d325 = %f\n", CPG_Result.dual->d325);
  printf("d326 = %f\n", CPG_Result.dual->d326);
  for(i=0; i<3; i++) {
    printf("d327[%d] = %f\n", i, CPG_Result.dual->d327[i]);
  }
  printf("d328 = %f\n", CPG_Result.dual->d328);
  printf("d329 = %f\n", CPG_Result.dual->d329);
  printf("d330 = %f\n", CPG_Result.dual->d330);
  printf("d331 = %f\n", CPG_Result.dual->d331);
  printf("d332 = %f\n", CPG_Result.dual->d332);
  for(i=0; i<3; i++) {
    printf("d333[%d] = %f\n", i, CPG_Result.dual->d333[i]);
  }
  printf("d334 = %f\n", CPG_Result.dual->d334);
  printf("d335 = %f\n", CPG_Result.dual->d335);
  printf("d336 = %f\n", CPG_Result.dual->d336);
  printf("d337 = %f\n", CPG_Result.dual->d337);
  printf("d338 = %f\n", CPG_Result.dual->d338);
  for(i=0; i<3; i++) {
    printf("d339[%d] = %f\n", i, CPG_Result.dual->d339[i]);
  }
  printf("d340 = %f\n", CPG_Result.dual->d340);
  printf("d341 = %f\n", CPG_Result.dual->d341);
  printf("d342 = %f\n", CPG_Result.dual->d342);
  printf("d343 = %f\n", CPG_Result.dual->d343);
  printf("d344 = %f\n", CPG_Result.dual->d344);
  for(i=0; i<3; i++) {
    printf("d345[%d] = %f\n", i, CPG_Result.dual->d345[i]);
  }
  printf("d346 = %f\n", CPG_Result.dual->d346);
  printf("d347 = %f\n", CPG_Result.dual->d347);
  printf("d348 = %f\n", CPG_Result.dual->d348);
  printf("d349 = %f\n", CPG_Result.dual->d349);
  printf("d350 = %f\n", CPG_Result.dual->d350);
  for(i=0; i<3; i++) {
    printf("d351[%d] = %f\n", i, CPG_Result.dual->d351[i]);
  }
  printf("d352 = %f\n", CPG_Result.dual->d352);
  printf("d353 = %f\n", CPG_Result.dual->d353);
  printf("d354 = %f\n", CPG_Result.dual->d354);
  printf("d355 = %f\n", CPG_Result.dual->d355);
  printf("d356 = %f\n", CPG_Result.dual->d356);
  for(i=0; i<3; i++) {
    printf("d357[%d] = %f\n", i, CPG_Result.dual->d357[i]);
  }
  printf("d358 = %f\n", CPG_Result.dual->d358);
  printf("d359 = %f\n", CPG_Result.dual->d359);
  printf("d360 = %f\n", CPG_Result.dual->d360);
  printf("d361 = %f\n", CPG_Result.dual->d361);
  printf("d362 = %f\n", CPG_Result.dual->d362);
  for(i=0; i<3; i++) {
    printf("d363[%d] = %f\n", i, CPG_Result.dual->d363[i]);
  }
  printf("d364 = %f\n", CPG_Result.dual->d364);
  printf("d365 = %f\n", CPG_Result.dual->d365);
  printf("d366 = %f\n", CPG_Result.dual->d366);
  printf("d367 = %f\n", CPG_Result.dual->d367);
  printf("d368 = %f\n", CPG_Result.dual->d368);
  for(i=0; i<3; i++) {
    printf("d369[%d] = %f\n", i, CPG_Result.dual->d369[i]);
  }
  printf("d370 = %f\n", CPG_Result.dual->d370);
  printf("d371 = %f\n", CPG_Result.dual->d371);
  printf("d372 = %f\n", CPG_Result.dual->d372);
  printf("d373 = %f\n", CPG_Result.dual->d373);
  printf("d374 = %f\n", CPG_Result.dual->d374);
  for(i=0; i<3; i++) {
    printf("d375[%d] = %f\n", i, CPG_Result.dual->d375[i]);
  }
  printf("d376 = %f\n", CPG_Result.dual->d376);
  printf("d377 = %f\n", CPG_Result.dual->d377);
  printf("d378 = %f\n", CPG_Result.dual->d378);
  printf("d379 = %f\n", CPG_Result.dual->d379);
  printf("d380 = %f\n", CPG_Result.dual->d380);
  for(i=0; i<3; i++) {
    printf("d381[%d] = %f\n", i, CPG_Result.dual->d381[i]);
  }
  printf("d382 = %f\n", CPG_Result.dual->d382);
  printf("d383 = %f\n", CPG_Result.dual->d383);
  printf("d384 = %f\n", CPG_Result.dual->d384);
  printf("d385 = %f\n", CPG_Result.dual->d385);
  printf("d386 = %f\n", CPG_Result.dual->d386);
  for(i=0; i<3; i++) {
    printf("d387[%d] = %f\n", i, CPG_Result.dual->d387[i]);
  }
  printf("d388 = %f\n", CPG_Result.dual->d388);
  printf("d389 = %f\n", CPG_Result.dual->d389);
  printf("d390 = %f\n", CPG_Result.dual->d390);
  printf("d391 = %f\n", CPG_Result.dual->d391);
  printf("d392 = %f\n", CPG_Result.dual->d392);
  for(i=0; i<3; i++) {
    printf("d393[%d] = %f\n", i, CPG_Result.dual->d393[i]);
  }
  printf("d394 = %f\n", CPG_Result.dual->d394);
  printf("d395 = %f\n", CPG_Result.dual->d395);
  printf("d396 = %f\n", CPG_Result.dual->d396);
  printf("d397 = %f\n", CPG_Result.dual->d397);
  printf("d398 = %f\n", CPG_Result.dual->d398);
  for(i=0; i<3; i++) {
    printf("d399[%d] = %f\n", i, CPG_Result.dual->d399[i]);
  }
  printf("d400 = %f\n", CPG_Result.dual->d400);
  printf("d401 = %f\n", CPG_Result.dual->d401);
  printf("d402 = %f\n", CPG_Result.dual->d402);
  printf("d403 = %f\n", CPG_Result.dual->d403);
  printf("d404 = %f\n", CPG_Result.dual->d404);
  for(i=0; i<3; i++) {
    printf("d405[%d] = %f\n", i, CPG_Result.dual->d405[i]);
  }
  printf("d406 = %f\n", CPG_Result.dual->d406);
  printf("d407 = %f\n", CPG_Result.dual->d407);
  printf("d408 = %f\n", CPG_Result.dual->d408);
  printf("d409 = %f\n", CPG_Result.dual->d409);
  printf("d410 = %f\n", CPG_Result.dual->d410);
  for(i=0; i<3; i++) {
    printf("d411[%d] = %f\n", i, CPG_Result.dual->d411[i]);
  }
  printf("d412 = %f\n", CPG_Result.dual->d412);
  printf("d413 = %f\n", CPG_Result.dual->d413);
  printf("d414 = %f\n", CPG_Result.dual->d414);
  printf("d415 = %f\n", CPG_Result.dual->d415);
  printf("d416 = %f\n", CPG_Result.dual->d416);
  for(i=0; i<3; i++) {
    printf("d417[%d] = %f\n", i, CPG_Result.dual->d417[i]);
  }
  printf("d418 = %f\n", CPG_Result.dual->d418);
  printf("d419 = %f\n", CPG_Result.dual->d419);
  printf("d420 = %f\n", CPG_Result.dual->d420);
  printf("d421 = %f\n", CPG_Result.dual->d421);
  printf("d422 = %f\n", CPG_Result.dual->d422);
  for(i=0; i<3; i++) {
    printf("d423[%d] = %f\n", i, CPG_Result.dual->d423[i]);
  }
  printf("d424 = %f\n", CPG_Result.dual->d424);
  printf("d425 = %f\n", CPG_Result.dual->d425);
  printf("d426 = %f\n", CPG_Result.dual->d426);
  printf("d427 = %f\n", CPG_Result.dual->d427);
  printf("d428 = %f\n", CPG_Result.dual->d428);
  for(i=0; i<3; i++) {
    printf("d429[%d] = %f\n", i, CPG_Result.dual->d429[i]);
  }
  printf("d430 = %f\n", CPG_Result.dual->d430);
  printf("d431 = %f\n", CPG_Result.dual->d431);
  printf("d432 = %f\n", CPG_Result.dual->d432);
  printf("d433 = %f\n", CPG_Result.dual->d433);
  printf("d434 = %f\n", CPG_Result.dual->d434);
  for(i=0; i<3; i++) {
    printf("d435[%d] = %f\n", i, CPG_Result.dual->d435[i]);
  }
  printf("d436 = %f\n", CPG_Result.dual->d436);
  printf("d437 = %f\n", CPG_Result.dual->d437);
  printf("d438 = %f\n", CPG_Result.dual->d438);
  printf("d439 = %f\n", CPG_Result.dual->d439);
  printf("d440 = %f\n", CPG_Result.dual->d440);
  for(i=0; i<3; i++) {
    printf("d441[%d] = %f\n", i, CPG_Result.dual->d441[i]);
  }
  printf("d442 = %f\n", CPG_Result.dual->d442);
  printf("d443 = %f\n", CPG_Result.dual->d443);
  printf("d444 = %f\n", CPG_Result.dual->d444);
  printf("d445 = %f\n", CPG_Result.dual->d445);
  printf("d446 = %f\n", CPG_Result.dual->d446);
  for(i=0; i<3; i++) {
    printf("d447[%d] = %f\n", i, CPG_Result.dual->d447[i]);
  }
  printf("d448 = %f\n", CPG_Result.dual->d448);
  printf("d449 = %f\n", CPG_Result.dual->d449);
  printf("d450 = %f\n", CPG_Result.dual->d450);
  printf("d451 = %f\n", CPG_Result.dual->d451);
  printf("d452 = %f\n", CPG_Result.dual->d452);
  for(i=0; i<3; i++) {
    printf("d453[%d] = %f\n", i, CPG_Result.dual->d453[i]);
  }
  printf("d454 = %f\n", CPG_Result.dual->d454);
  printf("d455 = %f\n", CPG_Result.dual->d455);
  printf("d456 = %f\n", CPG_Result.dual->d456);
  printf("d457 = %f\n", CPG_Result.dual->d457);
  printf("d458 = %f\n", CPG_Result.dual->d458);
  for(i=0; i<3; i++) {
    printf("d459[%d] = %f\n", i, CPG_Result.dual->d459[i]);
  }
  printf("d460 = %f\n", CPG_Result.dual->d460);
  printf("d461 = %f\n", CPG_Result.dual->d461);
  printf("d462 = %f\n", CPG_Result.dual->d462);
  printf("d463 = %f\n", CPG_Result.dual->d463);
  printf("d464 = %f\n", CPG_Result.dual->d464);
  for(i=0; i<3; i++) {
    printf("d465[%d] = %f\n", i, CPG_Result.dual->d465[i]);
  }
  printf("d466 = %f\n", CPG_Result.dual->d466);
  printf("d467 = %f\n", CPG_Result.dual->d467);
  printf("d468 = %f\n", CPG_Result.dual->d468);
  printf("d469 = %f\n", CPG_Result.dual->d469);
  printf("d470 = %f\n", CPG_Result.dual->d470);
  for(i=0; i<3; i++) {
    printf("d471[%d] = %f\n", i, CPG_Result.dual->d471[i]);
  }
  printf("d472 = %f\n", CPG_Result.dual->d472);
  printf("d473 = %f\n", CPG_Result.dual->d473);
  printf("d474 = %f\n", CPG_Result.dual->d474);
  printf("d475 = %f\n", CPG_Result.dual->d475);
  printf("d476 = %f\n", CPG_Result.dual->d476);
  for(i=0; i<3; i++) {
    printf("d477[%d] = %f\n", i, CPG_Result.dual->d477[i]);
  }
  printf("d478 = %f\n", CPG_Result.dual->d478);
  printf("d479 = %f\n", CPG_Result.dual->d479);
  printf("d480 = %f\n", CPG_Result.dual->d480);
  printf("d481 = %f\n", CPG_Result.dual->d481);
  printf("d482 = %f\n", CPG_Result.dual->d482);
  for(i=0; i<3; i++) {
    printf("d483[%d] = %f\n", i, CPG_Result.dual->d483[i]);
  }
  printf("d484 = %f\n", CPG_Result.dual->d484);
  printf("d485 = %f\n", CPG_Result.dual->d485);
  printf("d486 = %f\n", CPG_Result.dual->d486);
  printf("d487 = %f\n", CPG_Result.dual->d487);
  printf("d488 = %f\n", CPG_Result.dual->d488);
  for(i=0; i<3; i++) {
    printf("d489[%d] = %f\n", i, CPG_Result.dual->d489[i]);
  }
  printf("d490 = %f\n", CPG_Result.dual->d490);
  printf("d491 = %f\n", CPG_Result.dual->d491);
  printf("d492 = %f\n", CPG_Result.dual->d492);
  printf("d493 = %f\n", CPG_Result.dual->d493);
  printf("d494 = %f\n", CPG_Result.dual->d494);
  for(i=0; i<3; i++) {
    printf("d495[%d] = %f\n", i, CPG_Result.dual->d495[i]);
  }
  printf("d496 = %f\n", CPG_Result.dual->d496);
  printf("d497 = %f\n", CPG_Result.dual->d497);
  printf("d498 = %f\n", CPG_Result.dual->d498);
  printf("d499 = %f\n", CPG_Result.dual->d499);
  printf("d500 = %f\n", CPG_Result.dual->d500);
  for(i=0; i<3; i++) {
    printf("d501[%d] = %f\n", i, CPG_Result.dual->d501[i]);
  }
  printf("d502 = %f\n", CPG_Result.dual->d502);
  printf("d503 = %f\n", CPG_Result.dual->d503);
  printf("d504 = %f\n", CPG_Result.dual->d504);
  printf("d505 = %f\n", CPG_Result.dual->d505);
  printf("d506 = %f\n", CPG_Result.dual->d506);
  for(i=0; i<3; i++) {
    printf("d507[%d] = %f\n", i, CPG_Result.dual->d507[i]);
  }
  printf("d508 = %f\n", CPG_Result.dual->d508);
  printf("d509 = %f\n", CPG_Result.dual->d509);
  printf("d510 = %f\n", CPG_Result.dual->d510);
  printf("d511 = %f\n", CPG_Result.dual->d511);
  printf("d512 = %f\n", CPG_Result.dual->d512);
  for(i=0; i<3; i++) {
    printf("d513[%d] = %f\n", i, CPG_Result.dual->d513[i]);
  }
  printf("d514 = %f\n", CPG_Result.dual->d514);
  printf("d515 = %f\n", CPG_Result.dual->d515);
  printf("d516 = %f\n", CPG_Result.dual->d516);
  printf("d517 = %f\n", CPG_Result.dual->d517);
  printf("d518 = %f\n", CPG_Result.dual->d518);
  for(i=0; i<3; i++) {
    printf("d519[%d] = %f\n", i, CPG_Result.dual->d519[i]);
  }
  printf("d520 = %f\n", CPG_Result.dual->d520);
  printf("d521 = %f\n", CPG_Result.dual->d521);
  printf("d522 = %f\n", CPG_Result.dual->d522);
  printf("d523 = %f\n", CPG_Result.dual->d523);
  printf("d524 = %f\n", CPG_Result.dual->d524);
  for(i=0; i<3; i++) {
    printf("d525[%d] = %f\n", i, CPG_Result.dual->d525[i]);
  }
  printf("d526 = %f\n", CPG_Result.dual->d526);
  printf("d527 = %f\n", CPG_Result.dual->d527);
  printf("d528 = %f\n", CPG_Result.dual->d528);
  printf("d529 = %f\n", CPG_Result.dual->d529);
  printf("d530 = %f\n", CPG_Result.dual->d530);
  for(i=0; i<3; i++) {
    printf("d531[%d] = %f\n", i, CPG_Result.dual->d531[i]);
  }
  printf("d532 = %f\n", CPG_Result.dual->d532);
  printf("d533 = %f\n", CPG_Result.dual->d533);
  printf("d534 = %f\n", CPG_Result.dual->d534);
  printf("d535 = %f\n", CPG_Result.dual->d535);
  printf("d536 = %f\n", CPG_Result.dual->d536);
  for(i=0; i<3; i++) {
    printf("d537[%d] = %f\n", i, CPG_Result.dual->d537[i]);
  }
  printf("d538 = %f\n", CPG_Result.dual->d538);
  printf("d539 = %f\n", CPG_Result.dual->d539);
  printf("d540 = %f\n", CPG_Result.dual->d540);
  printf("d541 = %f\n", CPG_Result.dual->d541);
  printf("d542 = %f\n", CPG_Result.dual->d542);
  for(i=0; i<3; i++) {
    printf("d543[%d] = %f\n", i, CPG_Result.dual->d543[i]);
  }
  printf("d544 = %f\n", CPG_Result.dual->d544);
  printf("d545 = %f\n", CPG_Result.dual->d545);
  printf("d546 = %f\n", CPG_Result.dual->d546);
  printf("d547 = %f\n", CPG_Result.dual->d547);
  printf("d548 = %f\n", CPG_Result.dual->d548);
  for(i=0; i<3; i++) {
    printf("d549[%d] = %f\n", i, CPG_Result.dual->d549[i]);
  }
  printf("d550 = %f\n", CPG_Result.dual->d550);
  printf("d551 = %f\n", CPG_Result.dual->d551);
  printf("d552 = %f\n", CPG_Result.dual->d552);
  printf("d553 = %f\n", CPG_Result.dual->d553);
  printf("d554 = %f\n", CPG_Result.dual->d554);
  for(i=0; i<3; i++) {
    printf("d555[%d] = %f\n", i, CPG_Result.dual->d555[i]);
  }
  printf("d556 = %f\n", CPG_Result.dual->d556);
  printf("d557 = %f\n", CPG_Result.dual->d557);
  printf("d558 = %f\n", CPG_Result.dual->d558);
  printf("d559 = %f\n", CPG_Result.dual->d559);
  printf("d560 = %f\n", CPG_Result.dual->d560);
  for(i=0; i<3; i++) {
    printf("d561[%d] = %f\n", i, CPG_Result.dual->d561[i]);
  }
  printf("d562 = %f\n", CPG_Result.dual->d562);
  printf("d563 = %f\n", CPG_Result.dual->d563);
  printf("d564 = %f\n", CPG_Result.dual->d564);
  printf("d565 = %f\n", CPG_Result.dual->d565);
  printf("d566 = %f\n", CPG_Result.dual->d566);
  for(i=0; i<3; i++) {
    printf("d567[%d] = %f\n", i, CPG_Result.dual->d567[i]);
  }
  printf("d568 = %f\n", CPG_Result.dual->d568);
  printf("d569 = %f\n", CPG_Result.dual->d569);
  printf("d570 = %f\n", CPG_Result.dual->d570);
  printf("d571 = %f\n", CPG_Result.dual->d571);
  printf("d572 = %f\n", CPG_Result.dual->d572);
  for(i=0; i<3; i++) {
    printf("d573[%d] = %f\n", i, CPG_Result.dual->d573[i]);
  }
  printf("d574 = %f\n", CPG_Result.dual->d574);
  printf("d575 = %f\n", CPG_Result.dual->d575);
  printf("d576 = %f\n", CPG_Result.dual->d576);
  printf("d577 = %f\n", CPG_Result.dual->d577);
  printf("d578 = %f\n", CPG_Result.dual->d578);
  for(i=0; i<3; i++) {
    printf("d579[%d] = %f\n", i, CPG_Result.dual->d579[i]);
  }
  printf("d580 = %f\n", CPG_Result.dual->d580);
  printf("d581 = %f\n", CPG_Result.dual->d581);
  printf("d582 = %f\n", CPG_Result.dual->d582);
  printf("d583 = %f\n", CPG_Result.dual->d583);
  printf("d584 = %f\n", CPG_Result.dual->d584);
  for(i=0; i<3; i++) {
    printf("d585[%d] = %f\n", i, CPG_Result.dual->d585[i]);
  }
  printf("d586 = %f\n", CPG_Result.dual->d586);
  printf("d587 = %f\n", CPG_Result.dual->d587);
  printf("d588 = %f\n", CPG_Result.dual->d588);
  printf("d589 = %f\n", CPG_Result.dual->d589);
  printf("d590 = %f\n", CPG_Result.dual->d590);
  for(i=0; i<3; i++) {
    printf("d591[%d] = %f\n", i, CPG_Result.dual->d591[i]);
  }
  printf("d592 = %f\n", CPG_Result.dual->d592);
  printf("d593 = %f\n", CPG_Result.dual->d593);
  printf("d594 = %f\n", CPG_Result.dual->d594);
  printf("d595 = %f\n", CPG_Result.dual->d595);
  printf("d596 = %f\n", CPG_Result.dual->d596);
  for(i=0; i<3; i++) {
    printf("d597[%d] = %f\n", i, CPG_Result.dual->d597[i]);
  }
  printf("d598 = %f\n", CPG_Result.dual->d598);
  printf("d599 = %f\n", CPG_Result.dual->d599);
  printf("d600 = %f\n", CPG_Result.dual->d600);
  printf("d601 = %f\n", CPG_Result.dual->d601);
  printf("d602 = %f\n", CPG_Result.dual->d602);
  for(i=0; i<3; i++) {
    printf("d603[%d] = %f\n", i, CPG_Result.dual->d603[i]);
  }
  printf("d604 = %f\n", CPG_Result.dual->d604);
  printf("d605 = %f\n", CPG_Result.dual->d605);
  printf("d606 = %f\n", CPG_Result.dual->d606);
  printf("d607 = %f\n", CPG_Result.dual->d607);
  printf("d608 = %f\n", CPG_Result.dual->d608);
  for(i=0; i<3; i++) {
    printf("d609[%d] = %f\n", i, CPG_Result.dual->d609[i]);
  }
  printf("d610 = %f\n", CPG_Result.dual->d610);
  printf("d611 = %f\n", CPG_Result.dual->d611);
  printf("d612 = %f\n", CPG_Result.dual->d612);
  printf("d613 = %f\n", CPG_Result.dual->d613);
  printf("d614 = %f\n", CPG_Result.dual->d614);
  for(i=0; i<3; i++) {
    printf("d615[%d] = %f\n", i, CPG_Result.dual->d615[i]);
  }
  printf("d616 = %f\n", CPG_Result.dual->d616);
  printf("d617 = %f\n", CPG_Result.dual->d617);
  printf("d618 = %f\n", CPG_Result.dual->d618);
  printf("d619 = %f\n", CPG_Result.dual->d619);
  printf("d620 = %f\n", CPG_Result.dual->d620);
  for(i=0; i<3; i++) {
    printf("d621[%d] = %f\n", i, CPG_Result.dual->d621[i]);
  }
  printf("d622 = %f\n", CPG_Result.dual->d622);
  printf("d623 = %f\n", CPG_Result.dual->d623);
  printf("d624 = %f\n", CPG_Result.dual->d624);
  printf("d625 = %f\n", CPG_Result.dual->d625);
  printf("d626 = %f\n", CPG_Result.dual->d626);
  for(i=0; i<3; i++) {
    printf("d627[%d] = %f\n", i, CPG_Result.dual->d627[i]);
  }
  printf("d628 = %f\n", CPG_Result.dual->d628);
  printf("d629 = %f\n", CPG_Result.dual->d629);
  printf("d630 = %f\n", CPG_Result.dual->d630);
  printf("d631 = %f\n", CPG_Result.dual->d631);
  printf("d632 = %f\n", CPG_Result.dual->d632);
  for(i=0; i<3; i++) {
    printf("d633[%d] = %f\n", i, CPG_Result.dual->d633[i]);
  }
  printf("d634 = %f\n", CPG_Result.dual->d634);
  printf("d635 = %f\n", CPG_Result.dual->d635);
  printf("d636 = %f\n", CPG_Result.dual->d636);
  printf("d637 = %f\n", CPG_Result.dual->d637);
  printf("d638 = %f\n", CPG_Result.dual->d638);
  for(i=0; i<3; i++) {
    printf("d639[%d] = %f\n", i, CPG_Result.dual->d639[i]);
  }
  printf("d640 = %f\n", CPG_Result.dual->d640);
  printf("d641 = %f\n", CPG_Result.dual->d641);
  printf("d642 = %f\n", CPG_Result.dual->d642);
  printf("d643 = %f\n", CPG_Result.dual->d643);
  printf("d644 = %f\n", CPG_Result.dual->d644);
  for(i=0; i<3; i++) {
    printf("d645[%d] = %f\n", i, CPG_Result.dual->d645[i]);
  }
  printf("d646 = %f\n", CPG_Result.dual->d646);
  printf("d647 = %f\n", CPG_Result.dual->d647);
  printf("d648 = %f\n", CPG_Result.dual->d648);
  printf("d649 = %f\n", CPG_Result.dual->d649);
  printf("d650 = %f\n", CPG_Result.dual->d650);
  for(i=0; i<3; i++) {
    printf("d651[%d] = %f\n", i, CPG_Result.dual->d651[i]);
  }
  printf("d652 = %f\n", CPG_Result.dual->d652);
  printf("d653 = %f\n", CPG_Result.dual->d653);
  printf("d654 = %f\n", CPG_Result.dual->d654);
  printf("d655 = %f\n", CPG_Result.dual->d655);
  printf("d656 = %f\n", CPG_Result.dual->d656);
  for(i=0; i<3; i++) {
    printf("d657[%d] = %f\n", i, CPG_Result.dual->d657[i]);
  }
  printf("d658 = %f\n", CPG_Result.dual->d658);
  printf("d659 = %f\n", CPG_Result.dual->d659);
  printf("d660 = %f\n", CPG_Result.dual->d660);
  printf("d661 = %f\n", CPG_Result.dual->d661);
  printf("d662 = %f\n", CPG_Result.dual->d662);
  for(i=0; i<3; i++) {
    printf("d663[%d] = %f\n", i, CPG_Result.dual->d663[i]);
  }
  printf("d664 = %f\n", CPG_Result.dual->d664);
  printf("d665 = %f\n", CPG_Result.dual->d665);
  printf("d666 = %f\n", CPG_Result.dual->d666);
  printf("d667 = %f\n", CPG_Result.dual->d667);
  printf("d668 = %f\n", CPG_Result.dual->d668);
  for(i=0; i<3; i++) {
    printf("d669[%d] = %f\n", i, CPG_Result.dual->d669[i]);
  }
  printf("d670 = %f\n", CPG_Result.dual->d670);
  printf("d671 = %f\n", CPG_Result.dual->d671);
  printf("d672 = %f\n", CPG_Result.dual->d672);
  printf("d673 = %f\n", CPG_Result.dual->d673);
  printf("d674 = %f\n", CPG_Result.dual->d674);
  for(i=0; i<3; i++) {
    printf("d675[%d] = %f\n", i, CPG_Result.dual->d675[i]);
  }
  printf("d676 = %f\n", CPG_Result.dual->d676);
  printf("d677 = %f\n", CPG_Result.dual->d677);
  printf("d678 = %f\n", CPG_Result.dual->d678);
  printf("d679 = %f\n", CPG_Result.dual->d679);
  printf("d680 = %f\n", CPG_Result.dual->d680);
  for(i=0; i<3; i++) {
    printf("d681[%d] = %f\n", i, CPG_Result.dual->d681[i]);
  }
  printf("d682 = %f\n", CPG_Result.dual->d682);
  printf("d683 = %f\n", CPG_Result.dual->d683);
  printf("d684 = %f\n", CPG_Result.dual->d684);
  printf("d685 = %f\n", CPG_Result.dual->d685);
  printf("d686 = %f\n", CPG_Result.dual->d686);
  for(i=0; i<3; i++) {
    printf("d687[%d] = %f\n", i, CPG_Result.dual->d687[i]);
  }
  printf("d688 = %f\n", CPG_Result.dual->d688);
  printf("d689 = %f\n", CPG_Result.dual->d689);
  printf("d690 = %f\n", CPG_Result.dual->d690);
  printf("d691 = %f\n", CPG_Result.dual->d691);
  printf("d692 = %f\n", CPG_Result.dual->d692);
  for(i=0; i<3; i++) {
    printf("d693[%d] = %f\n", i, CPG_Result.dual->d693[i]);
  }
  printf("d694 = %f\n", CPG_Result.dual->d694);
  printf("d695 = %f\n", CPG_Result.dual->d695);
  printf("d696 = %f\n", CPG_Result.dual->d696);
  printf("d697 = %f\n", CPG_Result.dual->d697);
  printf("d698 = %f\n", CPG_Result.dual->d698);
  for(i=0; i<3; i++) {
    printf("d699[%d] = %f\n", i, CPG_Result.dual->d699[i]);
  }
  printf("d700 = %f\n", CPG_Result.dual->d700);
  printf("d701 = %f\n", CPG_Result.dual->d701);
  printf("d702 = %f\n", CPG_Result.dual->d702);
  printf("d703 = %f\n", CPG_Result.dual->d703);
  printf("d704 = %f\n", CPG_Result.dual->d704);
  for(i=0; i<3; i++) {
    printf("d705[%d] = %f\n", i, CPG_Result.dual->d705[i]);
  }
  printf("d706 = %f\n", CPG_Result.dual->d706);
  printf("d707 = %f\n", CPG_Result.dual->d707);
  printf("d708 = %f\n", CPG_Result.dual->d708);
  printf("d709 = %f\n", CPG_Result.dual->d709);
  printf("d710 = %f\n", CPG_Result.dual->d710);
  for(i=0; i<3; i++) {
    printf("d711[%d] = %f\n", i, CPG_Result.dual->d711[i]);
  }
  printf("d712 = %f\n", CPG_Result.dual->d712);
  printf("d713 = %f\n", CPG_Result.dual->d713);
  printf("d714 = %f\n", CPG_Result.dual->d714);
  printf("d715 = %f\n", CPG_Result.dual->d715);
  printf("d716 = %f\n", CPG_Result.dual->d716);
  for(i=0; i<3; i++) {
    printf("d717[%d] = %f\n", i, CPG_Result.dual->d717[i]);
  }
  printf("d718 = %f\n", CPG_Result.dual->d718);
  printf("d719 = %f\n", CPG_Result.dual->d719);
  printf("d720 = %f\n", CPG_Result.dual->d720);
  printf("d721 = %f\n", CPG_Result.dual->d721);
  printf("d722 = %f\n", CPG_Result.dual->d722);
  for(i=0; i<3; i++) {
    printf("d723[%d] = %f\n", i, CPG_Result.dual->d723[i]);
  }
  printf("d724 = %f\n", CPG_Result.dual->d724);
  printf("d725 = %f\n", CPG_Result.dual->d725);
  printf("d726 = %f\n", CPG_Result.dual->d726);
  printf("d727 = %f\n", CPG_Result.dual->d727);
  printf("d728 = %f\n", CPG_Result.dual->d728);
  for(i=0; i<3; i++) {
    printf("d729[%d] = %f\n", i, CPG_Result.dual->d729[i]);
  }
  printf("d730 = %f\n", CPG_Result.dual->d730);
  printf("d731 = %f\n", CPG_Result.dual->d731);
  printf("d732 = %f\n", CPG_Result.dual->d732);
  printf("d733 = %f\n", CPG_Result.dual->d733);
  printf("d734 = %f\n", CPG_Result.dual->d734);
  for(i=0; i<3; i++) {
    printf("d735[%d] = %f\n", i, CPG_Result.dual->d735[i]);
  }
  printf("d736 = %f\n", CPG_Result.dual->d736);
  printf("d737 = %f\n", CPG_Result.dual->d737);
  printf("d738 = %f\n", CPG_Result.dual->d738);
  printf("d739 = %f\n", CPG_Result.dual->d739);
  printf("d740 = %f\n", CPG_Result.dual->d740);
  for(i=0; i<3; i++) {
    printf("d741[%d] = %f\n", i, CPG_Result.dual->d741[i]);
  }
  printf("d742 = %f\n", CPG_Result.dual->d742);
  printf("d743 = %f\n", CPG_Result.dual->d743);
  printf("d744 = %f\n", CPG_Result.dual->d744);
  printf("d745 = %f\n", CPG_Result.dual->d745);
  printf("d746 = %f\n", CPG_Result.dual->d746);
  for(i=0; i<3; i++) {
    printf("d747[%d] = %f\n", i, CPG_Result.dual->d747[i]);
  }
  printf("d748 = %f\n", CPG_Result.dual->d748);
  printf("d749 = %f\n", CPG_Result.dual->d749);
  printf("d750 = %f\n", CPG_Result.dual->d750);
  printf("d751 = %f\n", CPG_Result.dual->d751);
  printf("d752 = %f\n", CPG_Result.dual->d752);
  for(i=0; i<3; i++) {
    printf("d753[%d] = %f\n", i, CPG_Result.dual->d753[i]);
  }
  printf("d754 = %f\n", CPG_Result.dual->d754);
  printf("d755 = %f\n", CPG_Result.dual->d755);
  printf("d756 = %f\n", CPG_Result.dual->d756);
  printf("d757 = %f\n", CPG_Result.dual->d757);
  printf("d758 = %f\n", CPG_Result.dual->d758);
  for(i=0; i<3; i++) {
    printf("d759[%d] = %f\n", i, CPG_Result.dual->d759[i]);
  }
  printf("d760 = %f\n", CPG_Result.dual->d760);
  printf("d761 = %f\n", CPG_Result.dual->d761);
  printf("d762 = %f\n", CPG_Result.dual->d762);
  printf("d763 = %f\n", CPG_Result.dual->d763);
  printf("d764 = %f\n", CPG_Result.dual->d764);
  for(i=0; i<3; i++) {
    printf("d765[%d] = %f\n", i, CPG_Result.dual->d765[i]);
  }
  printf("d766 = %f\n", CPG_Result.dual->d766);
  printf("d767 = %f\n", CPG_Result.dual->d767);
  printf("d768 = %f\n", CPG_Result.dual->d768);
  printf("d769 = %f\n", CPG_Result.dual->d769);
  printf("d770 = %f\n", CPG_Result.dual->d770);
  for(i=0; i<3; i++) {
    printf("d771[%d] = %f\n", i, CPG_Result.dual->d771[i]);
  }
  printf("d772 = %f\n", CPG_Result.dual->d772);
  printf("d773 = %f\n", CPG_Result.dual->d773);
  printf("d774 = %f\n", CPG_Result.dual->d774);
  printf("d775 = %f\n", CPG_Result.dual->d775);
  printf("d776 = %f\n", CPG_Result.dual->d776);
  for(i=0; i<3; i++) {
    printf("d777[%d] = %f\n", i, CPG_Result.dual->d777[i]);
  }
  printf("d778 = %f\n", CPG_Result.dual->d778);
  printf("d779 = %f\n", CPG_Result.dual->d779);
  printf("d780 = %f\n", CPG_Result.dual->d780);
  printf("d781 = %f\n", CPG_Result.dual->d781);
  printf("d782 = %f\n", CPG_Result.dual->d782);
  for(i=0; i<3; i++) {
    printf("d783[%d] = %f\n", i, CPG_Result.dual->d783[i]);
  }
  printf("d784 = %f\n", CPG_Result.dual->d784);
  printf("d785 = %f\n", CPG_Result.dual->d785);
  printf("d786 = %f\n", CPG_Result.dual->d786);
  printf("d787 = %f\n", CPG_Result.dual->d787);
  printf("d788 = %f\n", CPG_Result.dual->d788);
  for(i=0; i<3; i++) {
    printf("d789[%d] = %f\n", i, CPG_Result.dual->d789[i]);
  }
  printf("d790 = %f\n", CPG_Result.dual->d790);
  printf("d791 = %f\n", CPG_Result.dual->d791);
  printf("d792 = %f\n", CPG_Result.dual->d792);
  printf("d793 = %f\n", CPG_Result.dual->d793);
  printf("d794 = %f\n", CPG_Result.dual->d794);
  for(i=0; i<3; i++) {
    printf("d795[%d] = %f\n", i, CPG_Result.dual->d795[i]);
  }
  printf("d796 = %f\n", CPG_Result.dual->d796);
  printf("d797 = %f\n", CPG_Result.dual->d797);
  printf("d798 = %f\n", CPG_Result.dual->d798);
  printf("d799 = %f\n", CPG_Result.dual->d799);
  printf("d800 = %f\n", CPG_Result.dual->d800);
  for(i=0; i<3; i++) {
    printf("d801[%d] = %f\n", i, CPG_Result.dual->d801[i]);
  }
  printf("d802 = %f\n", CPG_Result.dual->d802);
  printf("d803 = %f\n", CPG_Result.dual->d803);
  printf("d804 = %f\n", CPG_Result.dual->d804);
  printf("d805 = %f\n", CPG_Result.dual->d805);
  printf("d806 = %f\n", CPG_Result.dual->d806);
  for(i=0; i<3; i++) {
    printf("d807[%d] = %f\n", i, CPG_Result.dual->d807[i]);
  }
  printf("d808 = %f\n", CPG_Result.dual->d808);
  printf("d809 = %f\n", CPG_Result.dual->d809);
  printf("d810 = %f\n", CPG_Result.dual->d810);
  printf("d811 = %f\n", CPG_Result.dual->d811);
  printf("d812 = %f\n", CPG_Result.dual->d812);
  for(i=0; i<3; i++) {
    printf("d813[%d] = %f\n", i, CPG_Result.dual->d813[i]);
  }
  printf("d814 = %f\n", CPG_Result.dual->d814);
  printf("d815 = %f\n", CPG_Result.dual->d815);
  printf("d816 = %f\n", CPG_Result.dual->d816);
  printf("d817 = %f\n", CPG_Result.dual->d817);
  printf("d818 = %f\n", CPG_Result.dual->d818);
  for(i=0; i<3; i++) {
    printf("d819[%d] = %f\n", i, CPG_Result.dual->d819[i]);
  }
  printf("d820 = %f\n", CPG_Result.dual->d820);
  printf("d821 = %f\n", CPG_Result.dual->d821);
  printf("d822 = %f\n", CPG_Result.dual->d822);
  printf("d823 = %f\n", CPG_Result.dual->d823);
  printf("d824 = %f\n", CPG_Result.dual->d824);
  for(i=0; i<3; i++) {
    printf("d825[%d] = %f\n", i, CPG_Result.dual->d825[i]);
  }
  printf("d826 = %f\n", CPG_Result.dual->d826);
  printf("d827 = %f\n", CPG_Result.dual->d827);
  printf("d828 = %f\n", CPG_Result.dual->d828);
  printf("d829 = %f\n", CPG_Result.dual->d829);
  printf("d830 = %f\n", CPG_Result.dual->d830);
  for(i=0; i<3; i++) {
    printf("d831[%d] = %f\n", i, CPG_Result.dual->d831[i]);
  }
  printf("d832 = %f\n", CPG_Result.dual->d832);
  printf("d833 = %f\n", CPG_Result.dual->d833);
  printf("d834 = %f\n", CPG_Result.dual->d834);
  printf("d835 = %f\n", CPG_Result.dual->d835);
  printf("d836 = %f\n", CPG_Result.dual->d836);
  for(i=0; i<3; i++) {
    printf("d837[%d] = %f\n", i, CPG_Result.dual->d837[i]);
  }
  printf("d838 = %f\n", CPG_Result.dual->d838);
  printf("d839 = %f\n", CPG_Result.dual->d839);
  printf("d840 = %f\n", CPG_Result.dual->d840);
  printf("d841 = %f\n", CPG_Result.dual->d841);
  printf("d842 = %f\n", CPG_Result.dual->d842);
  for(i=0; i<3; i++) {
    printf("d843[%d] = %f\n", i, CPG_Result.dual->d843[i]);
  }
  printf("d844 = %f\n", CPG_Result.dual->d844);
  printf("d845 = %f\n", CPG_Result.dual->d845);
  printf("d846 = %f\n", CPG_Result.dual->d846);
  printf("d847 = %f\n", CPG_Result.dual->d847);
  printf("d848 = %f\n", CPG_Result.dual->d848);
  for(i=0; i<3; i++) {
    printf("d849[%d] = %f\n", i, CPG_Result.dual->d849[i]);
  }
  printf("d850 = %f\n", CPG_Result.dual->d850);
  printf("d851 = %f\n", CPG_Result.dual->d851);
  printf("d852 = %f\n", CPG_Result.dual->d852);
  printf("d853 = %f\n", CPG_Result.dual->d853);
  printf("d854 = %f\n", CPG_Result.dual->d854);
  for(i=0; i<3; i++) {
    printf("d855[%d] = %f\n", i, CPG_Result.dual->d855[i]);
  }
  printf("d856 = %f\n", CPG_Result.dual->d856);
  printf("d857 = %f\n", CPG_Result.dual->d857);
  printf("d858 = %f\n", CPG_Result.dual->d858);
  printf("d859 = %f\n", CPG_Result.dual->d859);
  printf("d860 = %f\n", CPG_Result.dual->d860);
  for(i=0; i<3; i++) {
    printf("d861[%d] = %f\n", i, CPG_Result.dual->d861[i]);
  }
  printf("d862 = %f\n", CPG_Result.dual->d862);
  printf("d863 = %f\n", CPG_Result.dual->d863);
  printf("d864 = %f\n", CPG_Result.dual->d864);
  printf("d865 = %f\n", CPG_Result.dual->d865);
  printf("d866 = %f\n", CPG_Result.dual->d866);
  for(i=0; i<3; i++) {
    printf("d867[%d] = %f\n", i, CPG_Result.dual->d867[i]);
  }
  printf("d868 = %f\n", CPG_Result.dual->d868);
  printf("d869 = %f\n", CPG_Result.dual->d869);
  printf("d870 = %f\n", CPG_Result.dual->d870);
  printf("d871 = %f\n", CPG_Result.dual->d871);
  printf("d872 = %f\n", CPG_Result.dual->d872);
  for(i=0; i<3; i++) {
    printf("d873[%d] = %f\n", i, CPG_Result.dual->d873[i]);
  }
  printf("d874 = %f\n", CPG_Result.dual->d874);
  printf("d875 = %f\n", CPG_Result.dual->d875);
  printf("d876 = %f\n", CPG_Result.dual->d876);
  printf("d877 = %f\n", CPG_Result.dual->d877);
  printf("d878 = %f\n", CPG_Result.dual->d878);
  for(i=0; i<3; i++) {
    printf("d879[%d] = %f\n", i, CPG_Result.dual->d879[i]);
  }
  printf("d880 = %f\n", CPG_Result.dual->d880);
  printf("d881 = %f\n", CPG_Result.dual->d881);
  printf("d882 = %f\n", CPG_Result.dual->d882);
  printf("d883 = %f\n", CPG_Result.dual->d883);
  printf("d884 = %f\n", CPG_Result.dual->d884);
  for(i=0; i<3; i++) {
    printf("d885[%d] = %f\n", i, CPG_Result.dual->d885[i]);
  }
  printf("d886 = %f\n", CPG_Result.dual->d886);
  printf("d887 = %f\n", CPG_Result.dual->d887);
  printf("d888 = %f\n", CPG_Result.dual->d888);
  printf("d889 = %f\n", CPG_Result.dual->d889);
  printf("d890 = %f\n", CPG_Result.dual->d890);
  for(i=0; i<3; i++) {
    printf("d891[%d] = %f\n", i, CPG_Result.dual->d891[i]);
  }
  printf("d892 = %f\n", CPG_Result.dual->d892);
  printf("d893 = %f\n", CPG_Result.dual->d893);
  printf("d894 = %f\n", CPG_Result.dual->d894);
  printf("d895 = %f\n", CPG_Result.dual->d895);
  printf("d896 = %f\n", CPG_Result.dual->d896);
  for(i=0; i<3; i++) {
    printf("d897[%d] = %f\n", i, CPG_Result.dual->d897[i]);
  }
  printf("d898 = %f\n", CPG_Result.dual->d898);
  printf("d899 = %f\n", CPG_Result.dual->d899);
  printf("d900 = %f\n", CPG_Result.dual->d900);
  printf("d901 = %f\n", CPG_Result.dual->d901);
  printf("d902 = %f\n", CPG_Result.dual->d902);
  for(i=0; i<3; i++) {
    printf("d903[%d] = %f\n", i, CPG_Result.dual->d903[i]);
  }
  printf("d904 = %f\n", CPG_Result.dual->d904);
  printf("d905 = %f\n", CPG_Result.dual->d905);
  printf("d906 = %f\n", CPG_Result.dual->d906);
  printf("d907 = %f\n", CPG_Result.dual->d907);
  printf("d908 = %f\n", CPG_Result.dual->d908);
  for(i=0; i<3; i++) {
    printf("d909[%d] = %f\n", i, CPG_Result.dual->d909[i]);
  }
  printf("d910 = %f\n", CPG_Result.dual->d910);
  printf("d911 = %f\n", CPG_Result.dual->d911);
  printf("d912 = %f\n", CPG_Result.dual->d912);
  printf("d913 = %f\n", CPG_Result.dual->d913);
  printf("d914 = %f\n", CPG_Result.dual->d914);
  for(i=0; i<3; i++) {
    printf("d915[%d] = %f\n", i, CPG_Result.dual->d915[i]);
  }
  printf("d916 = %f\n", CPG_Result.dual->d916);
  printf("d917 = %f\n", CPG_Result.dual->d917);
  printf("d918 = %f\n", CPG_Result.dual->d918);
  printf("d919 = %f\n", CPG_Result.dual->d919);
  printf("d920 = %f\n", CPG_Result.dual->d920);
  for(i=0; i<3; i++) {
    printf("d921[%d] = %f\n", i, CPG_Result.dual->d921[i]);
  }
  printf("d922 = %f\n", CPG_Result.dual->d922);
  printf("d923 = %f\n", CPG_Result.dual->d923);
  printf("d924 = %f\n", CPG_Result.dual->d924);
  printf("d925 = %f\n", CPG_Result.dual->d925);
  printf("d926 = %f\n", CPG_Result.dual->d926);
  for(i=0; i<3; i++) {
    printf("d927[%d] = %f\n", i, CPG_Result.dual->d927[i]);
  }
  printf("d928 = %f\n", CPG_Result.dual->d928);
  printf("d929 = %f\n", CPG_Result.dual->d929);
  printf("d930 = %f\n", CPG_Result.dual->d930);
  printf("d931 = %f\n", CPG_Result.dual->d931);
  printf("d932 = %f\n", CPG_Result.dual->d932);
  for(i=0; i<3; i++) {
    printf("d933[%d] = %f\n", i, CPG_Result.dual->d933[i]);
  }
  printf("d934 = %f\n", CPG_Result.dual->d934);
  printf("d935 = %f\n", CPG_Result.dual->d935);
  printf("d936 = %f\n", CPG_Result.dual->d936);
  printf("d937 = %f\n", CPG_Result.dual->d937);
  printf("d938 = %f\n", CPG_Result.dual->d938);
  for(i=0; i<3; i++) {
    printf("d939[%d] = %f\n", i, CPG_Result.dual->d939[i]);
  }
  printf("d940 = %f\n", CPG_Result.dual->d940);
  printf("d941 = %f\n", CPG_Result.dual->d941);
  printf("d942 = %f\n", CPG_Result.dual->d942);
  printf("d943 = %f\n", CPG_Result.dual->d943);
  printf("d944 = %f\n", CPG_Result.dual->d944);
  for(i=0; i<3; i++) {
    printf("d945[%d] = %f\n", i, CPG_Result.dual->d945[i]);
  }
  printf("d946 = %f\n", CPG_Result.dual->d946);
  printf("d947 = %f\n", CPG_Result.dual->d947);
  printf("d948 = %f\n", CPG_Result.dual->d948);
  printf("d949 = %f\n", CPG_Result.dual->d949);
  printf("d950 = %f\n", CPG_Result.dual->d950);
  for(i=0; i<3; i++) {
    printf("d951[%d] = %f\n", i, CPG_Result.dual->d951[i]);
  }
  printf("d952 = %f\n", CPG_Result.dual->d952);
  printf("d953 = %f\n", CPG_Result.dual->d953);
  printf("d954 = %f\n", CPG_Result.dual->d954);
  printf("d955 = %f\n", CPG_Result.dual->d955);
  printf("d956 = %f\n", CPG_Result.dual->d956);
  for(i=0; i<3; i++) {
    printf("d957[%d] = %f\n", i, CPG_Result.dual->d957[i]);
  }
  printf("d958 = %f\n", CPG_Result.dual->d958);
  printf("d959 = %f\n", CPG_Result.dual->d959);
  printf("d960 = %f\n", CPG_Result.dual->d960);
  printf("d961 = %f\n", CPG_Result.dual->d961);
  printf("d962 = %f\n", CPG_Result.dual->d962);
  for(i=0; i<3; i++) {
    printf("d963[%d] = %f\n", i, CPG_Result.dual->d963[i]);
  }
  printf("d964 = %f\n", CPG_Result.dual->d964);
  printf("d965 = %f\n", CPG_Result.dual->d965);

  return 0;

}
